config/routes.rb
Rails.application.routes.draw do
  resources :clients

  root "pages#homebeta"
  get "about" => "pages#about"
  get "projects" => "pages#projects"
  get "contact" => "clients#new"
  get "techcorp" => "pages#techcorp"
  get "americanheart" => "pages#americanheart"
  get "overturemarketplace" => "pages#overturemarketplace"
  get "home" => "pages#home"

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end
  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json

  def create
    @client = Client.new(client_params)
    @client.save
    redirect_to contact_url, notice: 'Thank you for your message and look our for my reply.'
  end


  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :subject, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def projects
  end
  def contact
  end
  def homebeta
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-6 col-lg-offset-1">
      <div id="contact_form">
        <% if @client.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@client.errors.count, "error") %> prohibited this pin from being saved:</h2>
          <ul>
            <% @client.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
        <% if flash[:notice] %>
          <div class="alert alert-info" role="alert">
            <p>Thank you for your message. I will reply by the next day.</p>
        <% end %>
        </div>
      </div>
    </div>
  </div>
    <div class="row form_row">
      <div class="col-sm-7 col-md-8 col-lg-6 col-lg-offset-1">
        <div id="contact_form">
          <div id="contact_heading">
            <h2>Let's get in touch</h2><h4>and talk about UX in the Dallas area.</h4>
          </div>
          <div class="panel panel-default">
            <div class="panel-body">
              <%= form_for(@client) do |f| %>
              <div class="form-group">
                <h5 class="contact_label"><%= f.label :name %></h5>
                <%= f.text_field :name, class: "form-control input-lg" %>
              </div>
              <div class="form-group">
                <h5 class="contact_label"><%= f.label :email %></h5>
                <%= f.text_field :email, class: "form-control input-lg" %>
              </div>
              <div class="form-group">
                <h5 class="contact_label"><%= f.label :subject %></h5>
                <%= f.text_field :subject, class: "form-control input-lg" %>
              </div>
              <div class="form-group">
                <h5 class="contact_label"><%= f.label :message %></h5>
                <%= f.text_area :message, class: "form-control input-lg" %>
              </div>
              <div class="form-group">
                <%= f.submit "Send", class: "btn btn-primary btn-lg", id: "contact_send" %>
              </div>
              </div>

              <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-5 col-md-4 col-lg-3">
        <div id="contact_panel">
          <h3>Connect With Me</h3><br/>
          <h5>Email</h5><p><%= mail_to "victorestrada.ux@gmail.com", "victorestrada.ux@gmail.com", :class=>"connect_link" %></p>
          <h5>Twitter</h5><p><%= link_to "@victoreUNT", "https://twitter.com/victoreUNT", :class=>"connect_link" %></p>
          <h5>LinkedIn</h5><p><%= link_to "in/victor-estrada", "https://www.linkedin.com/in/victor-estrada-7927a2125", :class=>"connect_link" %></p>
          <h5>Mobile</h5><p><a href="tel:1-415-715-9039" class="connect_link">415-715-9039</a></p>
          <div><%= link_to "Victor's Resume", "resume.pdf", class: "btn btn-primary btn-lg", id: "download_resume" %></div>
        </div>
      </div>
  </div>
</div>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.subject %></td>
        <td><%= client.message %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<%= render 'form' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @client.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @client.message %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/_footer.html.erb
<!-- Old footer
<div id="footer_layout">
	<div class="container-fluid">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-1 col-sm-4 col-sm-offset-2 col-lg-3 col-lg-offset-3">
        <h6>Site</h6>
        <p><%= link_to 'Home', root_path, class: "footer-link" %></p>
        <p><%= link_to 'About', about_path, class: "footer-link" %></p>
        <p><%= link_to 'Projects', projects_path, class: "footer-link" %></p>
        <p><%= link_to "Resume", "resume.pdf", class: "footer-link" %></p>
        <p><%= link_to 'Contact', contact_path, class: "footer-link" %></p>
      </div>
      <div class="col-xs-4 col-xs-offset-2 col-sm-4 col-sm-offset-2 col-lg-3 col-lg-offset-2">
        <h6>Connect</h6>
        <p><%= link_to "Twitter", "https://twitter.com/victoreUNT", :class=>"footer-link" %></p>
        <p><%= link_to "LinkedIn", "https://www.linkedin.com/in/victor-estrada-7927a2125", :class=>"footer-link" %></p>
        <p><%= link_to "GitHub", "https://github.com/VictorEunt", :class=>"footer-link" %></p>
        <p><%= link_to "Blog", "https://uxwriting.wordpress.com/", :class=>"footer-link" %></p>
        <p><%= mail_to "victorestrada.ux@gmail.com", "Email Me", :class=>"footer-link" %></p>
      </div>
    </div>
  </div>
</div>
<div id="footer-note">
    <div class="container-fluid">
			<div class="row">
				<div class="col-xs-12">
          <h6 class="text-center">Developed with Ruby on Rails | <%= Date.today.year %></h6>
				</div>
		</div>
	</div>
</div>
-->
<div id="footer-update">
  <div class="container">
    <div class="row">
			<div class="col-xs-12 col-sm-5 col-md-6">
	    	<div id="footer-title" class="col-xs-12">Site</div>
	      <div class="col-xs-5 col-xs-offset-1 col-sm-5 col-sm-offset-0 col-md-4 col-md-offset-1 text-right">
	        <%= link_to 'Home', root_path, class: "btn btn-success btn-lg" %>
	      </div>
	      <div class="col-xs-5 col-sm-5 col-sm-offset-0 col-md-4 col-md-offset-0 text-left">
	        <%= link_to 'About', about_path, class: "btn btn-success btn-lg" %>
	      </div>
	      <div class="col-xs-5 col-xs-offset-1 col-sm-5 col-sm-offset-0 col-md-4 col-md-offset-1 text-right">
	        <%= link_to 'Projects', projects_path, class: "btn btn-success btn-lg" %>
	      </div>
	      <div class="col-xs-5 col-sm-5 col-sm-offset-0 col-md-4 col-md-offset-0 text-left">
	        <%= link_to 'Contact', contact_path, class: "btn btn-success btn-lg" %>
	      </div>
	      <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-0 col-md-10 col-md-offset-0">
	        <%= link_to "Resume", "resume.pdf", id: "resume-footer-button", class: "btn btn-success btn-block btn-lg" %>
	      </div>
		</div>

		<div class="col-sm-7 col-md-6">
	    <div id="footer-title" class="col-xs-12">Contact</div>
	    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0">
	      <a href="https://www.linkedin.com/in/victor-estrada-7927a2125" type="button" class="btn btn-danger btn-block btn-lg">
	        <span>
	          <i class="fa fa-linkedin" aria-hidden="true"></i>
	        </span><br>
	        <span id="footer-url">in/victor-estrada</span>
	      </a>
	    </div>
	    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0">
	      <a href="https://twitter.com/victoreUNT" type="button" class="btn btn-danger btn-block btn-lg">
	        <span>
	          <i class="fa fa-twitter" aria-hidden="true"></i>
	        </span><br>
	        <span id="footer-url">@victoreUNT</span>
	      </a>
	    </div>
	    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0">
	      <a href="mailto:victorestrada.ux@gmail.com" type="button" class="btn btn-danger btn-block btn-lg">
	        <span>
	          <i class="fa fa-envelope" aria-hidden="true"></i>
	        </span><br>
	        <span id="footer-url">victorestrada.ux@gmail.com</span>
	      </a>
	    </div>
	    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0">
	      <a href="tel:14157159039" type="button" class="btn btn-danger btn-block btn-lg">
	        <span>
	          <i class="fa fa-phone" aria-hidden="true"></i>
	        </span><br>
	        <span id="footer-url">415-715-9039</span>
	      </a>
	    </div>
	</div>


	</div>
</div>


	<div id="footer-signoff">
  	<div class="container">
	    <div class="row">
	      <div class="col-xs-12">
	        <div class="text-center">Designed with Sketch & Developed with Ruby on Rails | <span id="footer-date"><%= Date.today.year %></span>
	        </div>
	      </div>
	    </div>
	  </div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
    </button>
    <%= link_to image_tag("logo-updated.png", :alt=>'estrada logo', :class=>'navbar-brand'), root_path %>
		<p><%= link_to "Resume", 'resume.pdf', class: "navbar-text", id: "resume-link" %></p>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-collapse">
    <ul class="active nav navbar-nav navbar-right">
      <% if current_page?(root_path) %>
        <li class="<%= active_class(root_path) %>" id="home_option"><%= link_to "Home", root_path, class: "nav_link" %></li>
      <% else %>
        <li class="<%= active_class(root_path) %>"><%= link_to "Home", root_path, class: "nav_link" %></li>
      <% end %>
      <li class="<%= active_class(about_path) %>"><%= link_to "About", about_path, class: "nav_link" %></li>
      <li class="<%= active_class(projects_path) %>"><%= link_to "Projects", projects_path, class: "nav_link" %></li>
      <li><%= link_to "Resume", 'resume.pdf', class: "nav_link" %></li>
      <li class="<%= active_class(contact_path) %>"><%= link_to "Contact", contact_path, class: "nav_link" %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Victor's Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <meta name="description" content="A UX Portfolio developed by Victor Estrada, Master's in Technical Communication.">
  <meta name="keywords" content="ux, portfolio, victor estrada, unt, victor, estrada, university of north texas, denton, houston, texas, user experience, technical communication, content management, technical, writer, usability, cms, ruby, ruby on rails, web development, ux writer, ux developer, technical writer, content manager, ux research, drupal, card sort, personas, huxpa, twitter, linkedin, github, ux design, ux designer, user-centered design, front end development">
  <meta name="author" content="Victor Estrada, victor-estrada.com, Master's in Technical Communication authored the website with Ruby on Rails.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
<%= yield %>
	<%= render 'layouts/footer' %>
</body>

</html>

app/views/pages/about.html.erb
<div class="container-fluid about_header">
  <div class="page-header-default">
    <h1><small id="about">About <span id="about">Victor<br/></span>Graduating with a Master's in Technical Communication, I work with people every day to <span class="yellow_accent">research</span>, <span class="yellow_accent">test</span>, and <span class="yellow_accent">design</span> user-centered content.</small></h1>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-lg-5 col-lg-offset-1">
      <div id="about_box_1">
        <h3>My passion</h3>
				<h6>Practicing UX principles</h6>
        <p>I love working with people. After all, where would technology be without people? As a UX Specialist, I place the latest design methodologies at the forefront of my user research, testing, and design. Understanding how people desire to interact with technology and share information, I help create user-centered experiences driven by research and data.</p>
			</div>
		</div>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-lg-5 col-lg-offset-0">
      <div id="about_box_2">
        <h3>My past year</h3>
					<h6>Working with a Global UX Team</h6>
        <p>With Litehouse, a UX team with Harman International Industries, a subsidiary of Samsung, I have colloaborated with UX researchers, designers, and architects on vast, complex, and industry changing projects. I have completed expert evaluations on software, travelled across the U.S. to conduct contextual inquiries, collaborated to analyze and synthesize data, led usability testing, conducted a design mapping workshop, and created client-side deliverables.</p>
      </div>
    </div>
  </div>

  <div class="row tool_row">
   <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="recommend_header">
			<h2 id="engaging">My Tools Help Me Bring People Together</h2>
      <h3 id="workplace">Here are a few of my favorite.</h3>
    </div>
  </div>
</div>

 <div class="row logo_row">

		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<h5 class="logo_heading">Web Development</h5>
			<div class="col-xs-12 col-sm-6 col-md-6"><div class="logo"><%= link_to image_tag("git_logo.png", :alt=>'gihub logo', :id=>'git_logo') %></div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6"><div class="logo"><%= link_to image_tag("Ruby_on_Rails-logo2.png", :alt=>'ruby on rails logo', :id=>'rails_logo') %></div>
		 </div>
		</div>

	 <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
		<h5 class="logo_heading">UX Design</h5>
		<div class="col-xs-12 col-sm-6 col-md-6">
			<div class="logo"><%= link_to image_tag("morae-logo.png", :alt=>'morae', :id=>'morae_logo') %></div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-6">
			<div class="logo"><%= link_to image_tag("userzoom-logo.png", :alt=>'xml logo', :id=>'zoom_logo') %></div>
		</div>
	 </div>
	</div>

	<div class="row logo_row_2">
 <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
		<h5 class="logo_heading">Cloud-based Collaboration</h5>
		<div class="col-xs-12 col-sm-6 col-md-6">
		 <div class="logo"><%= link_to image_tag("slack.png", :alt=>'slack logo', :id=>'slack') %></div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-6">
			<div class="logo"><%= link_to image_tag("github_logo.png", :alt=>'github logo', :id=>'github') %></div>
		</div>
 </div>

	 <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
	  <h5 class="logo_heading">Technical Communication</h5>
		<div class="col-xs-12 col-sm-6 col-md-6">
			<div class="logo"><%= link_to image_tag("dita_2.png", :alt=>'dita logo', :id=>'dita_logo') %></div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-6">
			<div class="logo"><%= link_to image_tag("xml_logo2.png", :alt=>'xml logo', :id=>'xml_logo') %></div>
		</div>
	 </div>

 </div>


<div class="row workplace_row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="recommend_header">
      <h2 id="engaging">Making the Experience Engaging</h2>
      <h3 id="workplace">Workplace Testimonials</h3>
    </div>
  </div>
</div>

  <div class="row recommend_row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-4 col-lg-offset-0">
      <div class="recommend_box">
        <div class="photo_box">
          <%= link_to image_tag("hope_garcia.jpg", :alt=>'Kate Neal', :class=>'img-circle') %>
          <h4 class="box_name">Dr. Hope Garcia</h4>
          <h6 class="box_title">Executive Director<br/>of Student Affairs Administration</h6>
        </div>
        <p>"In his position, Victor has managed the difficult job of keeping our Division's web presence as cohesive as possible, while still meeting the needs of over 20 unique departments. And with his emotional intelligence, he is able to stay calm and work through difficult processes. Bringing this to the workplace takes a special talent that can still make the client feel heard, understood, and taken care of."</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8 col-md-offset-2 col-lg-4 col-lg-offset-0">
        <div class="recommend_box">
          <div class="photo_box">
            <%= link_to image_tag("kate_neal.jpg", :alt=>'Kate Neal', :class=>'img-circle') %>
            <h4 class="box_name">Kate Neal</h4>
					 <h6 class="box_title">Marketing Specialist</h6>
          </div>
          <p>“Victor goes above and beyond our divisions expectations on a regular basis. He puts usability and design at the forefront of every decision, no matter how small a decision it may be. He understands the complexity of managing content while making the experience engaging and enjoyable.”</p>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8 col-md-offset-2 col-lg-4 col-lg-offset-0">
        <div class="recommend_box">
          <div class="photo_box">
            <%= link_to image_tag("slee.jpg", :alt=>'Kate Neal', :class=>'img-circle') %>
            <h4 class="box_name">Stephanie Brown</h4>
            <h6 class="box_title">Assistant Director for Orientation<br/>and Transition Programs</h6>
          </div>
          <p>“Victor is an ideal person to collaborate with. He is very knowledgeable about the world of marketing and web design and is patient with his clients. Working with Victor is easy, in that he provides organized communication and produces polished websites. He is intentional about his designs and knows how to reach users.”</p>
        </div>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div id="home-page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <h1>Technical<br><span id="communicator">Communicator</span><br><small>UX Specialist</small></h1>
      </div>
      <div id="header-blurb" class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
        <p>Victor loves conducting research, testing, and designing for the end-user.</p>
      </div>
    </div>
  </div>
</div>
  <div id="home-styles">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <h2>Recent Projects</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-0">
          <div class="project-thumbnail-container">
            <div id="hover-effect">
              <a href="/overturemarketplace" class="thumbnail-link">
                <div class="thumbnail">
                   <%= image_tag('overture-background.png') %>
                    <div class="caption">
                      <h3>Student Loans: a Customer Journey</h3>
                      <p>With UX practices and usability testing, team recommendations were made for the Overture Marketplace site after testing with 37 participants using the remote-testing software, UserZoom.</p>
                    </div>
                </div>
              </a>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-0">
          <div class="project-thumbnail-container">
            <div id="hover-effect">
              <a href="/techcorp" class="thumbnail-link">
                <div class="thumbnail">
                   <%= image_tag('techcorp-home.png') %>
                    <div class="caption">
                      <h3>RESTful App for Academic Database</h3>
                      <p>After designing the objects and classes for a Postgres database, I developed an interface with embedded Ruby to upload and store a corpus of technical documents via Amazon Web Services.</p>
                    </div>
                </div>
              </a>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-0">
          <div class="project-thumbnail-container">
            <div id="hover-effect">
              <a href="/americanheart" class="thumbnail-link">
                <div class="thumbnail">
                   <%= image_tag('aha-logo-background.png') %>
                    <div class="caption">
                      <h3>Journalists on the Go: a Usability Study</h3>
                      <p>For an annual conference by the American Heart Association, I worked on a usability study and created recommendations for a Newsroom website, a conference intranet site for medical journalists.</p>
                    </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

<div id="endeavor-heading">
    <div class="container-fluid">
      <h2>My Endeavors</h2>
    </div>
</div>

  <div id="endeavor">
    <div class="container-fluid">
    </div>
  </div>

  <div id="endeavor-skills">
    <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 col-md-8 col-md-offset-2">
            <div class="even-well">
            <div class="well well-lg">
              <h2>Technical Editing and Documentation</h2>
              <p>Practiced in the project management of technical editing and copyediting for global audiences, I have applied these principles in developing procedures and documentation with DITA and have used Adobe CC to produce professional quality deliverables.</p>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <div class="odd-well">
            <div class="well well-lg">
              <h2>RESTful Programming and Development</h2>
              <p>I have practiced RESTful Programming and Development with the MVC framework Ruby on Rails. By conducting user research, architecting databases, and designing and programming user interfaces with an iterative process, I have first-hand experience working with the Scrum framework.</p>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <div class="even-well">
            <div class="well well-lg">
              <h2>Usability and Web Development</h2>
              <p>With companies including the American Heart Association, I have conducted data-centered enterprise usability testing with a focus on creating high-quality deliverables tailored to a variety of audiences. My usability and web projects both reflect a user-centered approach paired with a strong understanding of Typography, Print, and Web Design.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>